[package]
name = "rutils"
version = "0.1.0"
authors = ["yuer1727 <yuer1727@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.33"
structopt = { version = "0.2", default-features = false }
chrono = "0.4"


